services:
    nginx:
        image: nginx:latest
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./CertSSL:/etc/nginx/ssl
        depends_on:
            - starlio-web

    starlio-web:
        build: .
        ports:
            - '8000:8000'
        restart: unless-stopped
        volumes:
            - './CertSSL:/CertSSL'
            - './config.yaml:/config.yaml'

volumes:
    starlio-web:
        driver: local