services:
    starlio-web:
        build: .
        ports:
            - '8000:8000'
        restart: unless-stopped
        volumes:
            - './CertSSL:/CertSSL'
            - './config.yaml:/config.yaml'

volumes:
    starlio-web:
        driver: local